name: C++ build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install python libs
      working-directory: ./
      run: sudo pip install -r requirements.txt && cd ./utils/test_utils && sudo python3 setup.py install
    - name: build and test services
      working-directory: ./
      run: sudo bash ./build_and_test_all.sh
