name: C++ build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install boost
      run: sudo apt-get update && sudo apt-get install libboost-all-dev -y
    - name: cmake configure
      working-directory: ./
      env:
        BOOST_ROOT: /usr/include/boost
      run: cmake .
    - name: cmake build
      working-directory: ./
      run: cmake --build .
    - name: run unit tests
      working-directory: ./
      run: ./libraries/common/lib_common_tests && ./libraries/http/lib_http_tests && ./libraries/components/lib_components_tests
    - name: install python libs
      working-directory: ./
      run: python3 -m pip install -r requirements.txt && cd ./utils/test_utils && sudo python3 setup.py install
    - name: build and test services
      working-directory: ./
      run: ./build_and_test_all.sh
